/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;


#if !SILVERLIGHT
[Serializable]
#endif
[DataContract(Namespace="")]
public partial class AtlasListing : TBase
{
  private AtlasNodeInfo _node;
  private long _id;

  [DataMember]
  public AtlasNodeInfo Node
  {
    get
    {
      return _node;
    }
    set
    {
      __isset.node = true;
      this._node = value;
    }
  }

  [DataMember]
  public long Id
  {
    get
    {
      return _id;
    }
    set
    {
      __isset.id = true;
      this._id = value;
    }
  }


  public Isset __isset;
  #if !SILVERLIGHT
  [Serializable]
  #endif
  [DataContract]
  public struct Isset {
    public bool node;
    public bool id;
  }

  public AtlasListing() {
  }

  public void Read (TProtocol iprot)
  {
    TField field;
    iprot.ReadStructBegin();
    while (true)
    {
      field = iprot.ReadFieldBegin();
      if (field.Type == TType.Stop) { 
        break;
      }
      switch (field.ID)
      {
        case 1:
          if (field.Type == TType.Struct) {
            Node = new AtlasNodeInfo();
            Node.Read(iprot);
          } else { 
            TProtocolUtil.Skip(iprot, field.Type);
          }
          break;
        case 2:
          if (field.Type == TType.I64) {
            Id = iprot.ReadI64();
          } else { 
            TProtocolUtil.Skip(iprot, field.Type);
          }
          break;
        default: 
          TProtocolUtil.Skip(iprot, field.Type);
          break;
      }
      iprot.ReadFieldEnd();
    }
    iprot.ReadStructEnd();
  }

  public void Write(TProtocol oprot) {
    TStruct struc = new TStruct("AtlasListing");
    oprot.WriteStructBegin(struc);
    TField field = new TField();
    if (Node != null && __isset.node) {
      field.Name = "node";
      field.Type = TType.Struct;
      field.ID = 1;
      oprot.WriteFieldBegin(field);
      Node.Write(oprot);
      oprot.WriteFieldEnd();
    }
    if (__isset.id) {
      field.Name = "id";
      field.Type = TType.I64;
      field.ID = 2;
      oprot.WriteFieldBegin(field);
      oprot.WriteI64(Id);
      oprot.WriteFieldEnd();
    }
    oprot.WriteFieldStop();
    oprot.WriteStructEnd();
  }

  public override string ToString() {
    StringBuilder sb = new StringBuilder("AtlasListing(");
    sb.Append("Node: ");
    sb.Append(Node== null ? "<null>" : Node.ToString());
    sb.Append(",Id: ");
    sb.Append(Id);
    sb.Append(")");
    return sb.ToString();
  }

}

