/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;


#if !SILVERLIGHT
[Serializable]
#endif
[DataContract(Namespace="")]
public partial class AtlasMessage : TBase
{
  private string _data;
  private string _recipientKey;

  [DataMember]
  public string Data
  {
    get
    {
      return _data;
    }
    set
    {
      __isset.data = true;
      this._data = value;
    }
  }

  [DataMember]
  public string RecipientKey
  {
    get
    {
      return _recipientKey;
    }
    set
    {
      __isset.recipientKey = true;
      this._recipientKey = value;
    }
  }


  public Isset __isset;
  #if !SILVERLIGHT
  [Serializable]
  #endif
  [DataContract]
  public struct Isset {
    public bool data;
    public bool recipientKey;
  }

  public AtlasMessage() {
  }

  public void Read (TProtocol iprot)
  {
    TField field;
    iprot.ReadStructBegin();
    while (true)
    {
      field = iprot.ReadFieldBegin();
      if (field.Type == TType.Stop) { 
        break;
      }
      switch (field.ID)
      {
        case 1:
          if (field.Type == TType.String) {
            Data = iprot.ReadString();
          } else { 
            TProtocolUtil.Skip(iprot, field.Type);
          }
          break;
        case 2:
          if (field.Type == TType.String) {
            RecipientKey = iprot.ReadString();
          } else { 
            TProtocolUtil.Skip(iprot, field.Type);
          }
          break;
        default: 
          TProtocolUtil.Skip(iprot, field.Type);
          break;
      }
      iprot.ReadFieldEnd();
    }
    iprot.ReadStructEnd();
  }

  public void Write(TProtocol oprot) {
    TStruct struc = new TStruct("AtlasMessage");
    oprot.WriteStructBegin(struc);
    TField field = new TField();
    if (Data != null && __isset.data) {
      field.Name = "data";
      field.Type = TType.String;
      field.ID = 1;
      oprot.WriteFieldBegin(field);
      oprot.WriteString(Data);
      oprot.WriteFieldEnd();
    }
    if (RecipientKey != null && __isset.recipientKey) {
      field.Name = "recipientKey";
      field.Type = TType.String;
      field.ID = 2;
      oprot.WriteFieldBegin(field);
      oprot.WriteString(RecipientKey);
      oprot.WriteFieldEnd();
    }
    oprot.WriteFieldStop();
    oprot.WriteStructEnd();
  }

  public override string ToString() {
    StringBuilder sb = new StringBuilder("AtlasMessage(");
    sb.Append("Data: ");
    sb.Append(Data);
    sb.Append(",RecipientKey: ");
    sb.Append(RecipientKey);
    sb.Append(")");
    return sb.ToString();
  }

}

